version: "3.8"

services:
  node:
    container_name: wifievent-node
    image: wifievent-node:0.2.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - 3001:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 15
        npm run dev
    restart: unless-stopped
  db:
    container_name: wifievent-db
    image: mariadb:10
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_PW
      # - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PW
  adminer:
    container_name: wifievent-adminer
    image: adminer
    ports:
      - 8080:8080
